CREATE TABLE MEMBER (
  MEMID INTEGER(5)  NOT NULL AUTOINCREMENT,
  NAME VARCHAR(50) NOT NULL,
  DOB DATETIME,
  NUMBER_OF_BOOK_ALLOWED INTEGER(5),
  EMAIL VARCHAR(50),
  ADDRESS VARCHAR (80),
  MEM_IMG_ID VARCHAR (5),
  CONSTRAINT PK_MEMBER_ID PRIMARY KEY (MEMID) 
);
CREATE TABLE BOOK (
  BOOKID INTEGER(5) NOT NULL AUTOINCREMENT,
  PUBLISHER varchar(50),
  AUTHOR Varchar(50),
  CATEGORY varchar(20),
  AVAILABLE bool,
  PRICE INTEGER(20),
  year INTEGER(10),
  BOOK_IMG_ID varchar (5),
  CONSTRAINT PK_BOOK_ID PRIMARY KEY (BOOKID)
);
CREATE TABLE BORROW (
  MEMID INTEGER(5) NOT NULL,
  BOOKID INTEGER(5) NOT NULL,
  RESERVE_DATE datetime,
  DUE_DATE datetime,
  RETURN_DATE datetime,
  CONSTRAINT FK_MEMID FOREIGN key (MEMID) REFERENCES MEMBER(MEMID),
  CONSTRAINT FK_BOOKID FOREIGN key (BOOKID) REFERENCES BOOK(BOOKID),
  CONSTRAINT PK_BORROW PRIMARY KEY (MEMID,BOOKID)
  );
CREATE TABLE LOCATION (
  LOCA_ID varchar (5) NOT NULL,
  BOOKID INTEGER(5)NOT NULL,
  SHELF_ID intEGER(5),
  SECTION_ID intEGER(5), 
  ROW_NUMBER intEGER(5),
  CONSTRAINT FK_BOOKID FOREIGN KEY  (BOOKID) REFERENCES BOOK(BOOKID),
  CONSTRAINT PK_LOCATION_ID PRIMARY KEY (LOCA_ID)
  );